Title: Data Exploration
Author: Kolbe Sussman

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

## cleaned data

In [134]:
df = pd.read_csv("../data/processed/umich_works_cleaned.csv")
df.head()

,id,doi,title,authorships,topics,primary_topic,cited_by_count,publication_year,related_works,concepts,authorships_parsed,author_ids,author_names,institutions,raw_affiliations,topics_parsed,topic_ids,display_names,topic_scores
0,https://openalex.org/W4235678817,https://doi.org/10.1177/002224378101800104,Evaluating Structural Equation Models with Uno...,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10467', 'displa...","{'id': 'https://openalex.org/T10467', 'display...",64467,1981,"['https://openalex.org/W2614563012', 'https://...","[{'id': 'https://openalex.org/C2780695315', 'w...","[{'author_position': 'first', 'author': {'id':...","['https://openalex.org/A5047556013', 'https://...","['Claes Fornell', 'David F. Larcker']",['University of Michigan–Ann Arbor'],"['The University of Michigan', 'Northwestern U...","[{'id': 'https://openalex.org/T10467', 'displa...","['https://openalex.org/T10467', 'https://opena...","['Psychometric Methodologies and Testing', 'Mu...","[0.9793999791145325, 0.9490000009536743, 0.941..."
1,https://openalex.org/W1791587663,https://doi.org/10.2307/249008,"Perceived Usefulness, Perceived Ease of Use, a...","[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10068', 'displa...","{'id': 'https://openalex.org/T10068', 'display...",61935,1989,"['https://openalex.org/W4389670110', 'https://...","[{'id': 'https://openalex.org/C2776185967', 'w...","[{'author_position': 'first', 'author': {'id':...",['https://openalex.org/A5103061328'],['Fred D. Davis'],['University of Michigan–Ann Arbor'],['Computer and Information Systems'],"[{'id': 'https://openalex.org/T10068', 'displa...","['https://openalex.org/T10068', 'https://opena...","['Technology Adoption and User Behaviour', 'Kn...","[0.9998000264167786, 0.9921000003814697, 0.985..."
2,https://openalex.org/W1987258130,https://doi.org/10.2307/3151312,Evaluating Structural Equation Models with Uno...,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10467', 'displa...","{'id': 'https://openalex.org/T10467', 'display...",60116,1981,"['https://openalex.org/W2614563012', 'https://...","[{'id': 'https://openalex.org/C2780695315', 'w...","[{'author_position': 'first', 'author': {'id':...","['https://openalex.org/A5047556013', 'https://...","['Claes Fornell', 'David F. Larcker']","['University of Michigan–Ann Arbor', 'Northwes...","['Northwestern University****', 'U. Michigan#T...","[{'id': 'https://openalex.org/T10467', 'displa...","['https://openalex.org/T10467', 'https://opena...","['Psychometric Methodologies and Testing', 'Ad...","[0.9904999732971191, 0.9409000277519226]"
3,https://openalex.org/W2097117768,https://doi.org/10.1109/cvpr.2015.7298594,Going deeper with convolutions,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10036', 'displa...","{'id': 'https://openalex.org/T10036', 'display...",46263,2015,"['https://openalex.org/W2364252372', 'https://...","[{'id': 'https://openalex.org/C41008148', 'wik...","[{'author_position': 'first', 'author': {'id':...","['https://openalex.org/A5002183320', 'https://...","['Christian Szegedy', 'Wei Liu', 'Yangqing Jia...","['Magic Leap (United States)', 'Google (United...","['Google', 'IGoogle Inc', 'University of North...","[{'id': 'https://openalex.org/T10036', 'displa...","['https://openalex.org/T10036', 'https://opena...","['Advanced Neural Network Applications', 'Adva...","[0.9998999834060669, 0.9994999766349792, 0.999..."
4,https://openalex.org/W2117539524,https://doi.org/10.1007/s11263-015-0816-y,ImageNet Large Scale Visual Recognition Challenge,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10627', 'displa...","{'id': 'https://openalex.org/T10627', 'display...",39595,2015,"['https://openalex.org/W2095705906', 'https://...","[{'id': 'https://openalex.org/C185798385', 'wi...","[{'author_position': 'first', 'author': {'id':...","['https://openalex.org/A5022811687', 'https://...","['Olga Russakovsky', 'Jia Deng', 'Hao Su', 'Jo...","['University of North Carolina Health Care', '...","['UNC - Chapel Hill', 'Stanford University', '...","[{'id': 'https://openalex.org/T10627', 'displa...","['https://openalex.org/T10627', 'https://opena...",['Advanced Image and Video Retrieval Technique...,"[0.9998999834060669, 0.9995999932289124, 0.997..."

In [135]:
print(df.shape)
print(df.columns)
df.info()
df.describe()

(100000, 19)
Index(['id', 'doi', 'title', 'authorships', 'topics', 'primary_topic',
       'cited_by_count', 'publication_year', 'related_works', 'concepts',
       'authorships_parsed', 'author_ids', 'author_names', 'institutions',
       'raw_affiliations', 'topics_parsed', 'topic_ids', 'display_names',
       'topic_scores'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  100000 non-null  str
 1   doi                 98735 non-null   str
 2   title               99983 non-null   str
 3   authorships         100000 non-null  str
 4   topics              100000 non-null  str
 5   primary_topic       100000 non-null  str
 6   cited_by_count      100000 non-null  int64
 7   publication_year    100000 non-null  int64
 8   related_works       100000 non-null  str
 9   concepts            100000 non-null  str
 10  authorships_parsed  100000 non-null  str
 11  author_ids          100000 non-null  str
 12  author_names        100000 non-null  str
 13  institutions        100000 non-null  str
 14  raw_affiliations    100000 non-null  str
 15  topics_parsed       100000 non-null  str
 16  topic_ids           100000 non-null  str
 17  display_names       100000 non-null  str
 18  topic_scores        100000 non-null  str
dtypes: int64(2), str(17)
memory usage: 14.5 MB

       cited_by_count  publication_year
count   100000.000000     100000.000000
mean       180.332650       2009.731690
std        593.298715         10.892785
min          1.000000       1889.000000
25%         57.000000       2005.000000
50%         91.000000       2012.000000
75%        168.000000       2017.000000
max      64467.000000       2026.000000

In [118]:
s = df['authorships'][200]

lst = ast.literal_eval(s)
lst

[{'author_position': 'first',
  'author': {'id': 'https://openalex.org/A5041774458',
   'display_name': 'Barbara L. Fredrickson',
   'orcid': 'https://orcid.org/0000-0002-3890-2646'},
  'institutions': [{'id': 'https://openalex.org/I27837315',
    'display_name': 'University of Michigan–Ann Arbor',
    'ror': 'https://ror.org/00jmfr291',
    'country_code': 'US',
    'type': 'education',
    'lineage': ['https://openalex.org/I27837315']}],
  'countries': ['US'],
  'is_corresponding': True,
  'raw_author_name': 'Barbara L. Fredrickson',
  'raw_affiliation_strings': ['Department of Psychology, University of Michigan, 525 East University Avenue, Ann Arbor, MI 48109–1109, USA ()'],
  'affiliations': [{'raw_affiliation_string': 'Department of Psychology, University of Michigan, 525 East University Avenue, Ann Arbor, MI 48109–1109, USA ()',
    'institution_ids': ['https://openalex.org/I27837315']}]}]

In [119]:
s = df['topics'][200]

lst = ast.literal_eval(s)
lst

[{'id': 'https://openalex.org/T10475',
  'display_name': 'Psychological Well-being and Life Satisfaction',
  'score': 0.9995999932289124,
  'subfield': {'id': 'https://openalex.org/subfields/3207',
   'display_name': 'Social Psychology'},
  'field': {'id': 'https://openalex.org/fields/32',
   'display_name': 'Psychology'},
  'domain': {'id': 'https://openalex.org/domains/2',
   'display_name': 'Social Sciences'}},
 {'id': 'https://openalex.org/T12485',
  'display_name': 'Optimism, Hope, and Well-being',
  'score': 0.9968000054359436,
  'subfield': {'id': 'https://openalex.org/subfields/3202',
   'display_name': 'Applied Psychology'},
  'field': {'id': 'https://openalex.org/fields/32',
   'display_name': 'Psychology'},
  'domain': {'id': 'https://openalex.org/domains/2',
   'display_name': 'Social Sciences'}},
 {'id': 'https://openalex.org/T11433',
  'display_name': 'Emotional Intelligence and Performance',
  'score': 0.9891999959945679,
  'subfield': {'id': 'https://openalex.org/subfields/3207',
   'display_name': 'Social Psychology'},
  'field': {'id': 'https://openalex.org/fields/32',
   'display_name': 'Psychology'},
  'domain': {'id': 'https://openalex.org/domains/2',
   'display_name': 'Social Sciences'}}]

In [120]:
def extract_raw_affiliations(authorships):
    affiliations = []

    for author in authorships:
        for aff in author.get("affiliations", []):
            raw = aff.get("raw_affiliation_string")
            if raw:
                dept = raw.split(",")[0].strip()
                affiliations.append(dept)

    return list(set(affiliations))

df["raw_affiliations"] = df["authorships_parsed"].apply(extract_raw_affiliations)