Title: Data Exploration
Author: Kolbe Sussman

In [3]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

Matplotlib is building the font cache; this may take a moment.

## cleaned data

In [84]:
df = pd.read_csv("/Users/kolbesussman/Downloads/umich_works_selected_columns.csv") # local file
df.head()

,Unnamed: 0,id,doi,title,authorships,topics,primary_topic,cited_by_count,publication_year,related_works,concepts
0,0,https://openalex.org/W4235678817,https://doi.org/10.1177/002224378101800104,Evaluating Structural Equation Models with Uno...,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10467', 'displa...","{'id': 'https://openalex.org/T10467', 'display...",64212,1981,"['https://openalex.org/W2614563012', 'https://...","[{'id': 'https://openalex.org/C2780695315', 'w..."
1,1,https://openalex.org/W1791587663,https://doi.org/10.2307/249008,"Perceived Usefulness, Perceived Ease of Use, a...","[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10068', 'displa...","{'id': 'https://openalex.org/T10068', 'display...",61751,1989,"['https://openalex.org/W4389670110', 'https://...","[{'id': 'https://openalex.org/C2776185967', 'w..."
2,2,https://openalex.org/W1987258130,https://doi.org/10.2307/3151312,Evaluating Structural Equation Models with Uno...,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10467', 'displa...","{'id': 'https://openalex.org/T10467', 'display...",60073,1981,"['https://openalex.org/W2614563012', 'https://...","[{'id': 'https://openalex.org/C2780695315', 'w..."
3,3,https://openalex.org/W2097117768,https://doi.org/10.1109/cvpr.2015.7298594,Going deeper with convolutions,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10036', 'displa...","{'id': 'https://openalex.org/T10036', 'display...",46222,2015,"['https://openalex.org/W2364252372', 'https://...","[{'id': 'https://openalex.org/C41008148', 'wik..."
4,4,https://openalex.org/W2117539524,https://doi.org/10.1007/s11263-015-0816-y,ImageNet Large Scale Visual Recognition Challenge,"[{'author_position': 'first', 'author': {'id':...","[{'id': 'https://openalex.org/T10627', 'displa...","{'id': 'https://openalex.org/T10627', 'display...",39541,2015,"['https://openalex.org/W2095705906', 'https://...","[{'id': 'https://openalex.org/C185798385', 'wi..."

In [85]:
print(df.shape)
print(df.columns)
df.info()
df.describe()

(100000, 11)
Index(['Unnamed: 0', 'id', 'doi', 'title', 'authorships', 'topics',
       'primary_topic', 'cited_by_count', 'publication_year', 'related_works',
       'concepts'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        100000 non-null  int64
 1   id                100000 non-null  str
 2   doi               98776 non-null   str
 3   title             99984 non-null   str
 4   authorships       100000 non-null  str
 5   topics            100000 non-null  str
 6   primary_topic     100000 non-null  str
 7   cited_by_count    100000 non-null  int64
 8   publication_year  100000 non-null  int64
 9   related_works     100000 non-null  str
 10  concepts          100000 non-null  str
dtypes: int64(3), str(8)
memory usage: 8.4 MB

          Unnamed: 0  cited_by_count  publication_year
count  100000.000000   100000.000000     100000.000000
mean    49999.500000      179.024170       2010.063920
std     28867.657797      592.367952         10.976797
min         0.000000        1.000000       1889.000000
25%     24999.750000       57.000000       2005.000000
50%     49999.500000       91.000000       2012.000000
75%     74999.250000      168.000000       2018.000000
max     99999.000000    64212.000000       2026.000000

In [118]:
s = df['authorships'][200]

lst = ast.literal_eval(s)
lst

[{'author_position': 'first',
  'author': {'id': 'https://openalex.org/A5041774458',
   'display_name': 'Barbara L. Fredrickson',
   'orcid': 'https://orcid.org/0000-0002-3890-2646'},
  'institutions': [{'id': 'https://openalex.org/I27837315',
    'display_name': 'University of Michigan–Ann Arbor',
    'ror': 'https://ror.org/00jmfr291',
    'country_code': 'US',
    'type': 'education',
    'lineage': ['https://openalex.org/I27837315']}],
  'countries': ['US'],
  'is_corresponding': True,
  'raw_author_name': 'Barbara L. Fredrickson',
  'raw_affiliation_strings': ['Department of Psychology, University of Michigan, 525 East University Avenue, Ann Arbor, MI 48109–1109, USA ()'],
  'affiliations': [{'raw_affiliation_string': 'Department of Psychology, University of Michigan, 525 East University Avenue, Ann Arbor, MI 48109–1109, USA ()',
    'institution_ids': ['https://openalex.org/I27837315']}]}]

In [119]:
s = df['topics'][200]

lst = ast.literal_eval(s)
lst

[{'id': 'https://openalex.org/T10475',
  'display_name': 'Psychological Well-being and Life Satisfaction',
  'score': 0.9995999932289124,
  'subfield': {'id': 'https://openalex.org/subfields/3207',
   'display_name': 'Social Psychology'},
  'field': {'id': 'https://openalex.org/fields/32',
   'display_name': 'Psychology'},
  'domain': {'id': 'https://openalex.org/domains/2',
   'display_name': 'Social Sciences'}},
 {'id': 'https://openalex.org/T12485',
  'display_name': 'Optimism, Hope, and Well-being',
  'score': 0.9968000054359436,
  'subfield': {'id': 'https://openalex.org/subfields/3202',
   'display_name': 'Applied Psychology'},
  'field': {'id': 'https://openalex.org/fields/32',
   'display_name': 'Psychology'},
  'domain': {'id': 'https://openalex.org/domains/2',
   'display_name': 'Social Sciences'}},
 {'id': 'https://openalex.org/T11433',
  'display_name': 'Emotional Intelligence and Performance',
  'score': 0.9891999959945679,
  'subfield': {'id': 'https://openalex.org/subfields/3207',
   'display_name': 'Social Psychology'},
  'field': {'id': 'https://openalex.org/fields/32',
   'display_name': 'Psychology'},
  'domain': {'id': 'https://openalex.org/domains/2',
   'display_name': 'Social Sciences'}}]

In [120]:
def extract_raw_affiliations(authorships):
    affiliations = []

    for author in authorships:
        for aff in author.get("affiliations", []):
            raw = aff.get("raw_affiliation_string")
            if raw:
                dept = raw.split(",")[0].strip()
                affiliations.append(dept)

    return list(set(affiliations))

df["raw_affiliations"] = df["authorships_parsed"].apply(extract_raw_affiliations)

In [ ]:
lst = []

for row in df["raw_affiliations"]:
    for i in row:
        if i not in lst:
            lst.append(i)